# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Sun Jun 17 14:16:25 2012

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class MainMenuBar(wx.MenuBar):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainMenuBar.__init__
        wx.MenuBar.__init__(self, *args, **kwds)
        wxglade_tmp_menu = wx.Menu()
        self.Append(wxglade_tmp_menu, "Inputs")
        wxglade_tmp_menu = wx.Menu()
        self.Append(wxglade_tmp_menu, "Options")
        wxglade_tmp_menu = wx.Menu()
        self.Append(wxglade_tmp_menu, "Credits")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainMenuBar.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainMenuBar.__do_layout
        pass
        # end wxGlade

# end of class MainMenuBar
